export const catalogList = [
  // 肉・たまご
  {
    name: "牛バラ肉",
    category: "肉・たまご",
    categoryId: `${10}-${275}-${2134}`,
    image: "/image/肉/牛バラ肉.jpeg",
    tag: "Meat",
  },
  {
    name: "牛小間肉",
    category: "肉・たまご",
    categoryId: `${10}-${275}-${2135}`,
    image: "/image/肉/牛小間肉.jpeg",
    tag: "Meat",
  },
  {
    name: "牛ひき肉",
    category: "肉・たまご",
    categoryId: `${10}-${278}-${835}`,
    image: "/image/肉/牛ひき肉.jpeg",
    tag: "Meat",
  },
  {
    name: "卵",
    category: "肉・たまご",
    categoryId: `${33}-${367}-${1309}`,
    image: "/image/肉/たまご.jpeg",
    tag: "Meat",
  },
  {
    name: "鶏もも肉",
    category: "肉・たまご",
    categoryId: `${10}-${277}-${518}`,
    image: "/image/肉/とりもも肉.jpeg",
    tag: "Meat",
  },
  {
    name: "鶏むね肉",
    category: "肉・たまご",
    categoryId: `${10}-${277}-${1119}`,
    image: "/image/肉/とりむね肉.jpeg",
    tag: "Meat",
  },
  {
    name: "鶏ひき肉",
    category: "肉・たまご",
    categoryId: `${10}-${278}-${838}`,
    image: "/image/肉/とりひき肉.jpeg",
    tag: "Meat",
  },
  {
    name: "豚バラ肉",
    category: "肉・たまご",
    categoryId: `${10}-${276}-${830}`,
    image: "/image/肉/豚バラ肉.jpeg",
    tag: "Meat",
  },
  {
    name: "豚ロース肉",
    category: "肉・たまご",
    categoryId: `${10}-${276}-${1485}`,
    image: "/image/肉/豚ロース肉.jpeg",
    tag: "Meat",
  },
  {
    name: "豚ひき肉",
    category: "肉・たまご肉",
    categoryId: `${10}-${278}-${836}`,
    image: "/image/肉//豚ひき肉.jpeg",
    tag: "Meat",
  },
  {
    name: "ベーコン",
    category: "肉・たまご",
    categoryId: `${10}-${68}-${49}`,
    image: "/image/肉/ベーコン.jpeg",
    tag: "Meat",
  },
  // 魚
  {
    name: "あじ",
    category: "魚",
    categoryId: `${11}-${73}-${58}`,
    image: "/image/魚/あじ.jpeg",
    tag: "Fish",
  },
  {
    name: "いわし",
    category: "魚",
    categoryId: `${11}-${71}-${54}`,
    image: "/image/魚/いわし.jpeg",
    tag: "Fish",
  },
  {
    name: "カレイ",
    category: "魚",
    categoryId: `${11}-${78}-${323}`,
    image: "/image/魚/カレイ.jpeg",
    tag: "Fish",
  },
  {
    name: "サーモン",
    category: "魚",
    categoryId: `${11}-${70}-${839}`,
    image: "/image/魚/サーモン.jpeg",
    tag: "Fish",
  },
  {
    name: "さば",
    category: "魚",
    categoryId: `${11}-${72}-${322}`,
    image: "/image/魚/さば.jpeg",
    tag: "Fish",
  },
  {
    name: "ししゃも",
    category: "魚",
    categoryId: `${11}-${78}-${471}`,
    image: "/image/魚/ししゃも.jpeg",
    tag: "Fish",
  },
  {
    name: "鯛",
    category: "魚",
    categoryId: `${11}-${76}-${325}`,
    image: "/image/魚/鯛.jpeg",
    tag: "Fish",
  },
  {
    name: "ツナ缶",
    category: "魚",
    categoryId: `${13}-${109}-${843}`,
    image: "/image/魚/ツナ缶.jpeg",
    tag: "Fish",
  },
  {
    name: "ブリ",
    category: "魚",
    categoryId: `${11}-${74}-${57}`,
    image: "/image/魚/ブリ.jpeg",
    tag: "Fish",
  },
  {
    name: "マグロ",
    category: "魚",
    categoryId: `${11}-${77}-${53}`,
    image: "/image/魚/マグロ.jpeg",
    tag: "Fish",
  },
  // 乳製品
  {
    name: "カッテージチーズ",
    category: "乳製品",
    categoryId: `${13}-${482}-${1645}`,
    image: "/image/乳製品/カッテージチーズ.jpeg",
    tag: "DairyProduct",
  },
  {
    name: "カマンベールチーズ",
    category: "乳製品",
    categoryId: `${13}-${482}-${1642}`,
    image: "/image/乳製品/カマンベールチーズ.jpeg",
    tag: "DairyProduct",
  },
  {
    name: "牛乳",
    category: "乳製品",
    categoryId: `${27}-${268}-${266}`,
    image: "/image/乳製品/牛乳.jpeg",
    tag: "DairyProduct",
  },
  {
    name: "生クリーム",
    category: "乳製品",
    categoryId: `${21}-${218}-${1480}`,
    image: "/image/乳製品/生クリーム.jpeg",
    tag: "DairyProduct",
  },
  {
    name: "バター",
    category: "乳製品",
    categoryId: `${21}-${218}-${297}`,
    image: "/image/乳製品/バター.jpeg",
    tag: "DairyProduct",
  },
  {
    name: "モッツァレラチーズ",
    category: "乳製品",
    categoryId: `${13}-${482}-${1643}`,
    image: "/image/乳製品/モッツァレラチーズ.jpeg",
    tag: "DairyProduct",
  },
  {
    name: "ヨーグルト",
    category: "乳製品",
    categoryId: `${13}-${483}-${1647}`,
    image: "/image/乳製品/ヨーグルト.jpeg",
    tag: "DairyProduct",
  },
  // 野菜・きのこ
  {
    name: "アスパラガス",
    category: "野菜・きのこ",
    categoryId: `${12}-${100}-${11}`,
    image: "/image/野菜/アスパラガス.jpeg",
    tag: "Vegetable",
  },
  {
    name: "えのき",
    category: "野菜・きのこ",
    categoryId: `${12}-${105}-${78}`,
    image: "/image/野菜/えのき.jpeg",
    tag: "Vegetable",
  },
  {
    name: "かぼちゃ",
    category: "野菜・きのこ",
    categoryId: `${12}-${448}-${1519}`,
    image: "/image/野菜/かぼちゃ.jpeg",
    tag: "Vegetable",
  },
  {
    name: "キャベツ",
    category: "野菜・きのこ",
    categoryId: `${12}-${98}-${1}`,
    image: "/image/野菜/キャベツ.jpeg",
    tag: "Vegetable",
  },
  {
    name: "きゅうり",
    category: "野菜・きのこ",
    categoryId: `${12}-${450}-${1521}`,
    image: "/image/野菜/きゅうり.jpeg",
    tag: "Vegetable",
  },
  {
    name: "しいたけ",
    category: "野菜・きのこ",
    categoryId: `${12}-${105}-${75}`,
    image: "/image/野菜/しいたけ.jpeg",
    tag: "Vegetable",
  },
  {
    name: "しめじ",
    category: "野菜・きのこ",
    categoryId: `${12}-${105}-${76}`,
    image: "/image/野菜/しめじ.jpeg",
    tag: "Vegetable",
  },
  {
    name: "じゃがいも",
    category: "野菜・きのこ",
    categoryId: `${12}-${97}-${17}`,
    image: "/image/野菜/じゃがいも.jpeg",
    tag: "Vegetable",
  },
  {
    name: "大根",
    category: "野菜・きのこ",
    categoryId: `${12}-${449}-${1520}`,
    image: "/image/野菜/大根.jpeg",
    tag: "Vegetable",
  },
  {
    name: "たまねぎ",
    category: "野菜・きのこ",
    categoryId: `${12}-${96}-${7}`,
    image: "/image/野菜/たまねぎ.jpeg",
    tag: "Vegetable",
  },
  {
    name: "にんじん",
    category: "野菜・きのこ",
    categoryId: `${12}-${95}-${13}`,
    image: "/image/野菜/にんじん.jpeg",
    tag: "Vegetable",
  },
  {
    name: "ねぎ",
    category: "野菜・きのこ",
    categoryId: `${12}-${103}-${8}`,
    image: "/image/野菜/ねぎ.jpeg",
    tag: "Vegetable",
  },
  {
    name: "パプリカ",
    category: "野菜・きのこ",
    categoryId: `${12}-${101}-${456}`,
    image: "/image/野菜/パプリカ.jpeg",
    tag: "Vegetable",
  },
  {
    name: "ピーマン",
    category: "野菜・きのこ",
    categoryId: `${12}-${101}-${30}`,
    image: "/image/野菜/ピーマン.jpeg",
    tag: "Vegetable",
  },
  {
    name: "白菜",
    category: "野菜・きのこ",
    categoryId: `${12}-${453}-${1524}`,
    image: "/image/野菜/白菜.jpeg",
    tag: "Vegetable",
  },
  {
    name: "ブロッコリー",
    category: "野菜・きのこ",
    categoryId: `${12}-${458}-${1529}`,
    image: "/image/野菜/ブロッコリー.jpeg",
    tag: "Vegetable",
  },
  {
    name: "レタス",
    category: "野菜・きのこ",
    categoryId: `${12}-${100}-${2}`,
    image: "/image/野菜/レタス.jpeg",
    tag: "Vegetable",
  },
  // 豆類
  {
    name: "枝豆",
    category: "豆類",
    categoryId: `${12}-${101}-${24}`,
    image: "/image/豆類/枝豆.jpeg",
    tag: "Beans",
  },
  {
    name: "えんどう豆",
    category: "豆類",
    categoryId: `${12}-${100}-${21}`,
    image: "/image/豆類/えんどう豆.jpeg",
    tag: "Beans",
  },
  {
    name: "きな粉",
    category: "豆類",
    categoryId: `${13}-${481}-${1630}`,
    image: "/image/豆類/きな粉.jpeg",
    tag: "Beans",
  },
  {
    name: "絹ごし豆腐",
    category: "豆類",
    categoryId: `${35}-${472}-${1615}`,
    image: "/image/豆類/絹ごし豆腐.jpeg",
    tag: "Beans",
  },
  {
    name: "グリーンピース",
    category: "豆類",
    categoryId: `${12}-${100}-${844}`,
    image: "/image/豆類/グリーンピース.jpeg",
    tag: "Beans",
  },
  {
    name: "空豆",
    category: "豆類",
    categoryId: `${12}-${100}-${23}`,
    image: "/image/豆類/空豆.jpeg",
    tag: "Beans",
  },
  {
    name: "大豆",
    category: "豆類",
    categoryId: `${35}-${477}-${1620}`,
    image: "/image/豆類/大豆.jpeg",
    tag: "Beans",
  },
  {
    name: "豆乳",
    category: "豆類",
    categoryId: `${35}-${470}-${1613}`,
    image: "/image/豆類/豆乳.jpeg",
    tag: "Beans",
  },
  {
    name: "納豆",
    category: "豆類",
    categoryId: `${35}-${468}-${1611}`,
    image: "/image/豆類/納豆.jpeg",
    tag: "Beans",
  },
  {
    name: "木綿豆腐",
    category: "豆類",
    categoryId: `${35}-${471}-${1614}`,
    image: "/image/豆類/木綿豆腐.jpeg",
    tag: "Beans",
  },
  // 果物
  {
    name: "アボカド",
    category: "果物",
    categoryId: `${12}-${451}-${1522}`,
    image: "/image/果物/アボカド.jpeg",
    tag: "Fruits",
  },
  {
    name: "いちご",
    category: "果物",
    categoryId: `${34}-${692}-${1965}`,
    image: "/image/果物/いちご.jpeg",
    tag: "Fruits",
  },
  {
    name: "オレンジ",
    category: "果物",
    categoryId: `${34}-${702}-${2002}`,
    image: "/image/果物/オレンジ.jpeg",
    tag: "Fruits",
  },
  {
    name: "キウイ",
    category: "果物",
    categoryId: `${34}-${691}-${1964}`,
    image: "/image/果物/キウイ.jpeg",
    tag: "Fruits",
  },
  {
    name: "グレープフルーツ",
    category: "果物",
    categoryId: `${34}-${690}-${1963}`,
    image: "/image/果物/グレープフルーツ.jpeg",
    tag: "Fruits",
  },
  {
    name: "パイナップル",
    category: "果物",
    categoryId: `${34}-${693}-${1979}`,
    image: "/image/果物/パイナップル.jpeg",
    tag: "Fruits",
  },
  {
    name: "バナナ",
    category: "果物",
    categoryId: `${34}-${697}-${1962}`,
    image: "/image/果物/バナナ.jpeg",
    tag: "Fruits",
  },
  {
    name: "ブルーベリー",
    category: "果物",
    categoryId: `${34}-${462}-${1552}`,
    image: "/image/果物/ブルーベリー.jpeg",
    tag: "Fruits",
  },
  {
    name: "マンゴー",
    category: "果物",
    categoryId: `${34}-${693}-${1980}`,
    image: "/image/果物/マンゴー.jpeg",
    tag: "Fruits",
  },
  {
    name: "リンゴ",
    category: "果物",
    categoryId: `${34}-${688}-${1961}`,
    image: "/image/果物/リンゴ.jpeg",
    tag: "Fruits",
  },
  {
    name: "レモン",
    category: "果物",
    categoryId: `${34}-${461}-${1551}`,
    image: "/image/果物/レモン.jpeg",
    tag: "Fruits",
  },
  // 粉物・麺
  {
    name: "うどん",
    category: "粉物・麺",
    categoryId: `${16}-${152}-${1336}`,
    image: "/image/粉物/うどん.jpeg",
    tag: "Powdered",
  },
  {
    name: "片栗粉",
    category: "粉物・麺",
    categoryId: `${13}-${481}-${2066}`,
    image: "/image/粉物/片栗粉.jpeg",
    tag: "Powdered",
  },
  {
    name: "カレー粉",
    category: "粉物・麺",
    categoryId: `${19}-${675}-${1578}`,
    image: "/image/粉物/カレー粉.jpeg",
    tag: "Powdered",
  },
  {
    name: "小麦粉",
    category: "粉物・麺",
    categoryId: `${13}-${481}-${1632}`,
    image: "/image/粉物/小麦粉.jpeg",
    tag: "Powdered",
  },
  {
    name: "そうめん",
    category: "粉物・麺",
    categoryId: `${16}-${154}-${151}`,
    image: "/image/粉物/そうめん.jpeg",
    tag: "Powdered",
  },
  {
    name: "蕎麦",
    category: "粉物・麺",
    categoryId: `${16}-${153}-${916}`,
    image: "/image/粉物/蕎麦.jpeg",
    tag: "Powdered",
  },
  {
    name: "パスタ",
    category: "粉物・麺",
    categoryId: `${15}-${146}-${158}`,
    image: "/image/粉物/パスタ.jpeg",
    tag: "Powdered",
  },
  {
    name: "ペンネ・マカロニ",
    category: "粉物・麺",
    categoryId: `${13}-${479}-${1627}`,
    image: "/image/粉物/ペンネ・マカロニ.jpeg",
    tag: "Powdered",
  },
  {
    name: "焼きそば",
    category: "粉物・麺",
    categoryId: `${16}-${155}-${152}`,
    image: "/image/粉物/焼きそば.jpeg",
    tag: "Powdered",
  },
  // 穀物
  {
    name: "オートミール",
    category: "穀物",
    categoryId: `${13}-${109}-${2064}`,
    image: "/image/穀物/オートミール.jpeg",
    tag: "Grains",
  },
  {
    name: "米",
    category: "穀物",
    categoryId: `${14}-${271}-${147}`,
    image: "/image/穀物/ごはん.jpeg",
    tag: "Grains",
  },
  {
    name: "食パン",
    category: "穀物",
    categoryId: `${22}-${434}-${1430}`,
    image: "/image/穀物/食パン.jpeg",
    tag: "Grains",
  },
  {
    name: "とうもろこし",
    category: "穀物",
    categoryId: `${12}-${101}-${422}`,
    image: "/image/穀物/とうもろこし.jpeg",
    tag: "Grains",
  },
  {
    name: "バゲット",
    category: "穀物",
    categoryId: `${22}-${219}-${165}`,
    image: "/image/穀物/バゲット.jpeg",
    tag: "Grains",
  },
  // 調味料・その他
  {
    name: "オイスターソース",
    category: "調味料・その他",
    categoryId: `${19}-${711}-${2072}`,
    image: "/image/調味料・その他/オイスターソース.jpeg",
    tag: "Seasoning",
  },
  {
    name: "オリーブオイル",
    category: "調味料・その他",
    categoryId: `${19}-${464}-${1584}`,
    image: "/image/調味料・その他/オリーブオイル.jpeg",
    tag: "Seasoning",
  },
  {
    name: "黒こしょう",
    category: "調味料・その他",
    // categoryId: `${19}-${464}-${1584}`,
    image: "/image/調味料・その他/黒こしょう.jpeg",
    tag: "Seasoning",
  },
  {
    name: "ケチャップ",
    category: "調味料・その他",
    // categoryId: `${}-${}-${}`,
    image: "/image/調味料・その他/ケチャップ.jpeg",
    tag: "Seasoning",
  },
  {
    name: "こしょう",
    category: "調味料・その他",
    // categoryId: `${}-${}-${}`,
    image: "/image/調味料・その他/こしょう.jpeg",
    tag: "Seasoning",
  },
  {
    name: "ごま油",
    category: "調味料・その他",
    categoryId: `${19}-${710}-${2071}`,
    image: "/image/調味料・その他/ごま油.jpeg",
    tag: "Seasoning",
  },
  {
    name: "砂糖",
    category: "調味料・その他",
    // categoryId: `${}-${}-${}`,
    image: "/image/調味料・その他/砂糖.jpeg",
    tag: "Seasoning",
  },
  {
    name: "サラダ油",
    category: "調味料・その他",
    // categoryId: `${}-${}-${}`,
    image: "/image/調味料・その他/サラダ油.jpeg",
    tag: "Seasoning",
  },
  {
    name: "塩",
    category: "調味料・その他",
    categoryId: `${13}-${484}-${1657}`,
    image: "/image/調味料・その他/塩.jpeg",
    tag: "Seasoning",
  },
  {
    name: "しょうゆ",
    category: "調味料・その他",
    categoryId: `${19}-${675}-${1579}`,
    image: "/image/調味料・その他/しょうゆ.jpeg",
    tag: "Seasoning",
  },
  {
    name: "ゼラチン",
    category: "調味料・その他",
    // categoryId: `${}-${}-${}`,
    image: "/image/調味料・その他/ゼラチン.jpeg",
    tag: "Seasoning",
  },
  {
    name: "マヨネーズ",
    category: "調味料・その他",
    categoryId: `${19}-${192}-${627}`,
    image: "/image/調味料・その他/マヨネーズ.jpeg",
    tag: "Seasoning",
  },
  {
    name: "味噌",
    category: "調味料・その他",
    categoryId: `${19}-${675}-${1568}`,
    image: "/image/調味料・その他/味噌.jpeg",
    tag: "Seasoning",
  },
  {
    name: "みりん",
    category: "調味料・その他",
    // categoryId: `${}-${}-${}`,
    image: "/image/調味料・その他/みりん.jpeg",
    tag: "Seasoning",
  },
  {
    name: "酒",
    category: "調味料・その他",
    // categoryId: `${}-${}-${}`,
    image: "/image/調味料・その他/料理酒.jpeg",
    tag: "Seasoning",
  },
];
